import React, { useState } from 'react';
import { Link } from 'react-router-dom';
import PlayerAvatar from './PlayerPortrait';

const sections = {
  Profile: [{title:'Position',detail:'Operations Manager · QA & Automation',text:'I connect day-to-day operations with data quality, structured testing, and practical automation.'},{title:'My strengths',text:'Finding gaps in workflows. Turning repetitive work into reliable processes. Coordinating across teams. Taking ownership from problem definition through delivery.'},{title:'Off the clock',text:'Basketball and League of Legends. Lakers faithful, T1 loyal. QA discipline. Automation mindset.'}],
  Experience: [{title:'GPS Logix',detail:'Operations Manager · 2024–Present | Database Manager · Jun 2016–Nov 2021',text:'Operational workflows, account coordination, data validation, and practical automation.',to:'/case-studies/gps-3pl-operations'},{title:'Studio Sai / Eternights',detail:'QA Engineer · Dec 2021–May 2024',text:'Structured testing and PlayStation release support.',to:'/case-studies/eternights-qa'}],
  Skills: [{title:'Quality & validation',text:'Manual and regression testing, defect reporting, UI-focused Unity Test Framework validation.',to:'/case-studies/eternights-qa'},{title:'Automation & systems',text:'Python, Google Apps Script, data transformation, Extensiv WMS, and operational workflows.',to:'/case-studies/gps-order-automation'},{title:'Web & cloud projects',text:'React, TypeScript, AWS setup, serverless workflows, and AI-assisted delivery.',to:'/case-studies/remembering-young-hoon'}],
  Projects: [{title:'Remembering Young Hoon',text:'A bilingual memorial archive. Independently led planning, feature decisions, AWS setup, and deployment.',to:'/case-studies/remembering-young-hoon'},{title:'Market Intelligence Lab',text:'In progress: validated market evidence and research toward an explainable score.',to:'/case-studies/market-intelligence-lab'},{title:'LAYRD',text:'Technical and operational support for an independent home goods brand.',to:'/case-studies/layrd-operations'}],
};

function StrengthBoard() {
  const strengths = [
    ['Operations', 'Warehouse & account workflows', '/case-studies/gps-3pl-operations'],
    ['Data quality', 'Transformation & validation', '/case-studies/gps-order-automation'],
    ['Automation', 'Python & Apps Script', '/case-studies/gps-order-automation'],
    ['Quality assurance', 'Regression & release delivery', '/case-studies/eternights-qa'],
    ['Ownership', 'From requirements to deployment', '/case-studies/remembering-young-hoon']
  ];
  return <section className="strength-board"><div className="board-top"><span>PLAYER STRENGTHS</span><span>PROVEN THROUGH WORK</span></div><div className="strength-body"><div>{strengths.map(([name,detail,to])=><Link className="strength-row" key={name} to={to}><span>{name}</span><span className="strength-evidence">{detail}</span><span aria-hidden="true">↗</span></Link>)}</div><blockquote><span aria-hidden="true">“</span><p>Same mindset.<br/>Different court.</p><small>DISCIPLINE.<br/>PROCESS.<br/>BETTER DAYS.</small></blockquote></div></section>;
}

function PlayingStyle() {
  return <section className="playing-style"><div className="board-top"><span>PLAYING STYLE</span></div><div className="style-grid">{[['◎','Problem solver','Find practical solutions'],['◈','Cross-functional','Connect people and systems'],['▥','Process driven','Make workflows repeatable'],['↗','Always learning','Build, test, and improve']].map(([icon,title,body])=><div key={title}><span className="style-icon" aria-hidden="true">{icon}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section>;
}
export default function CareerBoard(){const [active,setActive]=useState('Profile');return <section className="career-hero" id="home"><div className="career-heading"><p className="eyebrow">THE CAREER SCOREBOARD / VOL. 02</p><h1>Meet the player.<br/><span>Explore the work.</span></h1><p>Operations, quality, and automation. A look at the person behind the systems.</p></div><div className="career-layout"><PlayerAvatar/><div className="board-stack"><div className="career-board"><div className="board-top"><span>PLAYER PROFILE</span><span>77 / SJ</span></div><div className="board-tabs" role="tablist" aria-label="Career categories">{Object.keys(sections).map((name,i)=><button key={name} role="tab" id={`tab-${name}`} aria-selected={active===name} aria-controls="career-panel" onClick={()=>setActive(name)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();const keys=Object.keys(sections);const next=keys[(i+(e.key==='ArrowRight'?1:3))%4];setActive(next);document.getElementById(`tab-${next}`).focus();}}}><small>0{i+1}</small>{name}</button>)}</div><div id="career-panel" role="tabpanel" aria-labelledby={`tab-${active}`} className="board-content">{sections[active].map(item=><article key={item.title}><h2>{item.title}</h2>{item.detail&&<small>{item.detail}</small>}<p>{item.text}</p>{item.to&&<Link to={item.to}>Explore the work ↗</Link>}</article>)}</div><div className="board-footer"><a className="button primary" href={`${process.env.PUBLIC_URL}/resume/Sung_Jung_Resume.pdf`} download>Download resume ↓</a><a href="mailto:sungjung0616@gmail.com">Let’s talk ↗</a></div></div><StrengthBoard /><PlayingStyle /></div></div></section>;}

export function RecentPlays(){return <section className="recent-plays"><div className="section-heading"><p className="eyebrow">RECENT PLAYS</p><h2>The work behind the scoreboard.</h2></div><p className="plays-note">Selected build notes and delivery milestones.</p><div className="play-row"><span>01 / DESIGN UPDATE</span><div><h3>Portfolio v2 · Finding my home court</h3><p>Exploring an illustrated player profile, a browsable career board, and a purple-and-gold visual identity rooted in basketball.</p></div><span className="play-status">LOCAL PROTOTYPE</span></div><Link className="play-row" to="/case-studies/remembering-young-hoon"><span>02 / PROJECT DELIVERY</span><div><h3>Remembering Young Hoon</h3><p>From a personal purpose to a bilingual archive with review workflows, private media, and AWS image processing.</p></div><span className="play-status">VIEW CASE STUDY ↗</span></Link><Link className="play-row" to="/case-studies/market-intelligence-lab"><span>03 / RESEARCH</span><div><h3>Market Intelligence Lab</h3><p>Organizing market evidence while researching how an intuitive score can remain explainable.</p></div><span className="play-status">IN PROGRESS ↗</span></Link></section>;}
