import React from 'react';
import { Link } from 'react-router-dom';

const GPSOperationsCaseStudy = () => (
  <article className="case-study-page">
    <header className="case-study-hero">
      <Link className="back-link" to="/">← Selected work</Link>
      <p className="eyebrow">Case study 03 · 3PL operations</p>
      <h1>Designing operations<br /><span>for growing volume.</span></h1>
      <p className="case-study-lede">How I helped establish a new 3PL warehouse workflow, turned manual SKU grouping into a product requirement, and coordinated account operations at scale.</p>
      <dl className="case-facts"><div><dt>Role</dt><dd>Operations Manager</dd></div><div><dt>Company</dt><dd>GPS Logix</dd></div><div><dt>Period</dt><dd>2024 — Present</dd></div><div><dt>Environment</dt><dd>Extensiv WMS · Workpad OMS</dd></div></dl>
    </header>

    <section className="case-story"><aside><p className="eyebrow">Starting point</p><p className="aside-note">Client names and sensitive operational details are intentionally generalized.</p></aside><div><h2>A new 3PL operation needed more than software—it needed a working floor system.</h2><p>The operation began with approximately five client accounts and 3,000–3,500 daily orders. I helped set up computers, account-specific warehouse locations, WMS usage, packing flow, and the working procedures used to move orders from the OMS through fulfillment.</p></div></section>

    <section className="case-story"><aside><p className="eyebrow">The bottleneck</p></aside><div><h2>Processing orders only by time created unnecessary picking travel.</h2><p>When orders entered Extensiv in chronological order, workers repeatedly crossed the warehouse for different SKUs. The system sequence did not match the most efficient physical picking sequence.</p></div></section>

    <section className="case-story action-section"><aside><p className="eyebrow">The evolution</p></aside><div><h2>Validate the workflow manually, then improve the system.</h2><div className="step-list"><div><span>01</span><h3>Group similar orders</h3><p>Used Excel filters to divide orders into batches with similar SKUs before uploading them into the fulfillment workflow.</p></div><div><span>02</span><h3>Standardize work instructions</h3><p>Created a template for SKU, quantity, and label-reference information so batches could be assigned clearly to workers.</p></div><div><span>03</span><h3>Translate floor needs</h3><p>Defined the operational requirement for SKU-based order grouping based on observed picking constraints.</p></div><div><span>04</span><h3>Partner with development</h3><p>Worked with the AcrossB development team until automatic SKU separation was added to Workpad.</p></div></div></div></section>

    <section className="operations-scale"><p className="eyebrow">Operation supported</p><div className="scale-grid"><div><strong>3K–3.5K</strong><span>daily orders at launch</span></div><div><strong>~11K</strong><span>typical daily orders currently</span></div><div><strong>10</strong><span>client accounts currently</span></div></div><p className="scale-note">These figures describe the warehouse operation supported by the team. They are not presented as volume generated by one individual.</p></section>

    <section className="case-story scope-section"><aside><p className="eyebrow">My contribution</p></aside><div><h2>Connecting tools, people, and the physical workflow.</h2><div className="scope-grid"><div><h3>Operational ownership</h3><ul><li>Warehouse setup and account locations</li><li>Picking and packing flow design</li><li>Batching and work-instruction process</li><li>Day-to-day account and warehouse coordination</li><li>Inventory and order-risk communication</li></ul></div><div><h3>Collaboration boundary</h3><ul><li>Workpad was developed by AcrossB</li><li>Extensiv was used as the WMS, without custom API ownership</li><li>Warehouse output was achieved by the broader team</li><li>Client storefront and sales decisions remained client-owned</li><li>Confidential client and incident details are excluded</li></ul></div></div></div></section>

    <section className="case-next"><p className="eyebrow">Related GPS story</p><h2>See the earlier data automation work.</h2><Link className="button primary" to="/case-studies/gps-order-automation">Read order automation</Link></section>
  </article>
);

export default GPSOperationsCaseStudy;
