import React from 'react';
import { Link } from 'react-router-dom';

const MarketIntelligenceCaseStudy = () => (
  <article className="case-study-page market-lab-page">
    <header className="case-study-hero market-lab-hero">
      <Link className="back-link" to="/">&larr; Selected work</Link>
      <div className="build-status"><span className="status-dot" /> Active build &middot; Scoring methodology under research</div>
      <p className="eyebrow">Market Intelligence Lab</p>
      <h1>Understand the market.<br /><span>Without decoding every chart.</span></h1>
      <p className="case-study-lede">An in-progress research platform designed to translate fragmented market signals into an intuitive, explainable market-environment score.</p>
      <div className="hero-actions"><a className="button primary" href="https://github.com/SungJung0616/market-intelligence-lab" target="_blank" rel="noreferrer">View GitHub</a><a className="button secondary" href="#build-log">Follow the build log</a></div>
      <dl className="case-facts"><div><dt>Status</dt><dd>In progress</dd></div><div><dt>Current milestone</dt><dd>Evidence quality</dd></div><div><dt>Stack</dt><dd>Python &middot; Streamlit &middot; Plotly</dd></div><div><dt>Sources</dt><dd>FRED &middot; Tiingo &middot; Coinbase</dd></div></dl>
    </header>

    <section className="case-story compact-story"><aside><p className="eyebrow">Why it exists</p></aside><div><h2>The problem is not a lack of market data. It is making sense of disconnected signals.</h2><p>Financial platforms already provide indexes, charts, rates, volatility, currencies, and asset prices. People still have to interpret those signals separately before they can understand the overall environment.</p><p>I prefer systems that make complex information intuitive. Like a movie rating, a market score can provide a useful starting point - but only when the criteria, evidence, conflicts, and uncertainty remain visible.</p></div></section>

    <section className="score-concept-panel"><div className="score-preview"><p className="eyebrow">Product concept</p><strong>68</strong><span>Illustrative score &middot; Not a live result</span></div><div><h2>A simple score on the surface. A defensible method underneath.</h2><p>The product goal is to help someone understand the market environment at a glance. The research challenge is deciding which signals belong in the score, how they should be normalized and weighted, which historical baseline is appropriate, and how uncertainty should be communicated.</p></div></section>

    <section className="workflow-panel"><p className="eyebrow">Current evidence pipeline</p><div className="workflow-steps"><span>Collect</span><i>&rarr;</i><span>Validate</span><i>&rarr;</i><span>Normalize</span><i>&rarr;</i><span>Store</span><i>&rarr;</i><span>Summarize</span><i>&rarr;</i><span>Visualize</span><i>&rarr;</i><span>Test</span></div><p className="pipeline-note">Provider-specific collection logic remains separate while validated observations are converted into a shared internal model.</p></section>

    <section className="case-story action-section"><aside><p className="eyebrow">Working now</p><p className="aside-note">The evidence layer is implemented. Composite scoring and AI analysis are not.</p></aside><div><h2>Building reliable evidence before building interpretation.</h2><div className="step-list"><div><span>01</span><h3>Multi-provider collection</h3><p>Collects representative equity, rate, volatility, dollar, cross-asset, and Bitcoin observations from FRED, Tiingo, and Coinbase.</p></div><div><span>02</span><h3>Validation and normalization</h3><p>Validates provider responses, preserves source context, and converts approved observations into a consistent internal shape.</p></div><div><span>03</span><h3>Separated storage</h3><p>Stores generated data by provider and series so evidence remains traceable and is not silently mixed across sources.</p></div><div><span>04</span><h3>Tested research views</h3><p>Presents equity, macro, cross-asset, and Bitcoin evidence through Streamlit while using tests, linting, and strict type checks.</p></div></div></div></section>

    <section className="case-story scope-section"><aside><p className="eyebrow">Design decisions</p></aside><div><h2>Interpretation should never outrun the evidence.</h2><div className="decision-grid"><article><h3>Validate before interpreting</h3><p>Data must pass provider-specific checks before entering the shared research workflow.</p></article><article><h3>Separate collection from presentation</h3><p>The interface reads stored, validated evidence instead of calling providers directly.</p></article><article><h3>Keep scoring deterministic</h3><p>Future scores must use explicit, reproducible, versioned rules that can be tested historically.</p></article><article><h3>Use AI for explanation</h3><p>AI may explain evidence, conflicts, and uncertainty; it should not own or silently change the underlying score.</p></article></div></div></section>

    <section className="case-story"><aside><p className="eyebrow">What I own</p></aside><div><h2>Product boundaries, research questions, and acceptance criteria.</h2><p>I define the product direction, data-quality requirements, architecture boundaries, and criteria for each milestone. I use AI-assisted development tools to accelerate implementation, documentation, review, and learning, then validate behavior through source review, automated tests, live-data checks, and explicit implementation boundaries.</p></div></section>

    <section className="case-story roadmap-story"><aside><p className="eyebrow">Research roadmap</p></aside><div><h2>The scoring method is the product's central research problem.</h2><div className="scope-grid"><div><h3>Now</h3><ul><li>Expand and validate evidence coverage</li><li>Verify freshness and missing observations</li><li>Improve shared comparisons</li><li>Document provider and quality boundaries</li></ul></div><div><h3>Next</h3><ul><li>Define the first deterministic score input</li><li>Research normalization and weighting</li><li>Establish historical validation criteria</li><li>Add confidence and conflicting evidence</li></ul></div></div><div className="not-implemented"><p className="eyebrow">Not implemented</p><p>Stock prediction &middot; Investment recommendations &middot; Automated trading &middot; Composite market score &middot; Risk-On/Risk-Off classification &middot; AI-generated conclusions</p></div></div></section>

    <section className="build-log" id="build-log"><div className="section-heading"><p className="eyebrow">Build log</p><h2>Follow the system as it develops.</h2></div><div className="build-log-list"><article><time>Aug 9, 2026</time><div><h3>Evidence coverage expanded</h3><p>Completed collection, validation, storage, summaries, and research views for representative equity, macro, cross-asset, and Bitcoin evidence.</p></div></article><article><time>Aug 9, 2026</time><div><h3>Research interface organized</h3><p>Separated the Streamlit preview into four evidence-focused views so unlike signals remain distinguishable.</p></div></article><article><time>Aug 9, 2026</time><div><h3>Interpretation boundary documented</h3><p>Separated observable evidence, future deterministic scoring, and future AI explanation into distinct responsibilities.</p></div></article></div><a className="case-link external-case-link" href="https://github.com/SungJung0616/market-intelligence-lab" target="_blank" rel="noreferrer">Review the code and commit history <span>↗</span></a></section>

    <section className="case-next"><p className="eyebrow">Explore another system</p><h2>Operational data transformed for reliable downstream delivery.</h2><Link className="button primary" to="/case-studies/gps-order-automation">Read the GPS automation case study</Link></section>
  </article>
);

export default MarketIntelligenceCaseStudy;
